---
- name: Gitlab Server
  hosts: gitlab
  become: yes
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    - common
    - gitlab

- name: Redmine Server
  hosts: redmine
  become: yes
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    - common
    - ruby
    - { role: postgres, db_name: redmine, db_passwd: "{{ db_passwd_redmine }}" }
    - redmine
    - passenger

- name: Ldap Server
  hosts: ldap
  become: yes
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    - common
#    - ldap
    - java8
#    - tomcat
#    - pwm
