---
- name: Activiti
  hosts: activiti
  become: yes
  vars_files:
    - proxy.yml
  environment: "{{ proxy_env }}"
  roles:
    - common
    - { role: postgres, db_name: activiti, db_passwd: "{{ db_passwd_activiti }}" }
    - tomcat
    - { role: activiti, db_name: activiti, db_passwd: "{{ db_passwd_activiti }}" }
