- name: Configure nginx
  hosts: testserver
  become: True
  tasks:

    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    - name: Add gpg key of EPEL
      rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 state=present

    - name: Install nginx
      yum: name=nginx state=latest

    - name: copy nginx config file
      copy: src=files/nginx/site-ansible.conf dest=/etc/nginx/default.d/

    - name: Creates /ansible site directory
      file: path=/var/www/ansible state=directory owner=nginx group=nginx mode=0775

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/var/www/ansible/index.html

    - name: start nginx
      service: name=nginx enabled=Yes state=started

