# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all" # machine group on the ansible hosts file.
    ansible.inventory_path = "hosts"
    ansible.playbook = "nginx.yml"
  end
end
