---
- name: Check whether redmine was installed or not
  stat: path={{ JAVA_DL_PATH }}
  register: java8

- name: Download oracle jdk 1.8
  get_url:
    url="{{ JAVA_DL_URL }}"
    dest="{{ JAVA_DL_PATH }}"
    headers="Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'"
    validate_certs=no
    owner=root
    group=root
    mode=744
  when: not java8.stat.exists

- name: Install oracle jdk 1.8
  yum: name={{ JAVA_DL_PATH }}
