---
##########
# RM+ common lib
- name: install RM+ a_common_libs plugin
  git:
    repo=https://bitbucket.org/dkuk/a_common_libs.git
    dest={{ redmine_dir }}/plugins/a_common_libs

##########
## Knowledgebase
# we must install this plugin to the directory "/plugins/redmine_knowledgebase" exactly.
- name: install knowledgebase plugin
  git:
    repo=https://github.com/alexbevi/redmine_knowledgebase.git
    dest={{ redmine_dir }}/plugins/redmine_knowledgebase
    force=yes

- name: apply patch to /var/lib/redmine/plugins/redmine_knowledgebase/Gemfile
  patch: >
    src=knowledgebase_Gemfile.diff
    dest=/var/lib/redmine/plugins/redmine_knowledgebase/Gemfile
    backup=yes
  ignore_errors: yes

##########
## time logger
- name: install time_logger plugin
  git:
    repo=https://github.com/speedy32129/time_logger.git
    dest={{ redmine_dir }}/plugins/time_logger

##########
## default custome query
- name: install redmine_default_custom_query plugin
  git:
    repo=https://github.com/hidakatsuya/redmine_default_custom_query.git
    dest={{ redmine_dir }}/plugins/redmine_default_custom_query

##########
## issue template
- name: install redmine_issue_templates plugin
  git:
    repo=https://github.com/akiko-pusu/redmine_issue_templates.git
    dest={{ redmine_dir }}/plugins/redmine_issue_templates

##########
## backlog
- name: install backlogs plugin for redmine 3
  git:
    repo=https://github.com/backlogs/redmine_backlogs.git
    version=origin/feature/redmine3
    dest={{ redmine_dir }}/plugins/redmine_backlogs
    force=yes

# To Create the patch file:
# 1. login remote redmine server
# 2. backup Gemfile to Gemfile.org
# 3. change Gemfile
# 4. exit redmine server to ansible host
# 5. run remote diff command from ansible host
#    $ vagrant ssh redmine -- sudo diff /var/lib/redmine/plugins/redmine_backlogs/Gemfile.org /var/lib/redmine/plugins/redmine_backlogs/Gemfile
- name: apply patch to /var/lib/redmine/plugins/redmine_backlogs/Gemfile
  patch: >
    src=backlogs_Gemfile.diff
    dest=/var/lib/redmine/plugins/redmine_backlogs/Gemfile
    backup=yes
  ignore_errors: yes

##########
## lightbox2
- name: install redmine_lightbox2 plugin
  git:
    repo=https://github.com/paginagmbh/redmine_lightbox2.git
    dest={{ redmine_dir }}/plugins/redmine_lightbox2

##########
## theme changer
- name: install redmine_theme_changer plugin
  hg:
    repo=https://bitbucket.org/haru_iida/redmine_theme_changer
    dest={{ redmine_dir }}/plugins/redmine_theme_changer

##########
## local avatars
- name: install redmine_local_avatars plugin
  git:
    repo=https://github.com/ncoders/redmine_local_avatars.git
    dest={{ redmine_dir }}/plugins/redmine_local_avatars

##########
## EasyGanttFree
- name: install EasyGanttFree
  unarchive:
    src=files/EasyGanttFree.zip
    dest={{ redmine_dir }}/plugins
  ignore_errors: yes

# [TODO] RM+ Userbility
# [TODO] RM+ Custom Menu

- name: delete Gemfile.lock
  file: path={{ redmine_dir }}/Gemfile.lock state=absent

- name: install plugin gems
  command:
    bundle install --no-deployment
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: update gems
  command:
    bundle update
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: migrate redmine-database
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: migrate plugins-database
  command:
    bundle exec rake redmine:plugins:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
