---
# OAuth
# - name: install oauth_provider plugin
#  git:
#    repo=https://github.com/suer/redmine_oauth_provider
#    dest={{ redmine_dir }}/plugins/oauth_provider

# RM+ common lib
- name: install RM+ a_common_libs plugin
  git:
    repo=https://bitbucket.org/dkuk/a_common_libs.git
    dest={{ redmine_dir }}/plugins/a_common_libs

- name: install favourite_projects plugin
  git:
    repo=https://github.com/syntacticvexation/redmine_favourite_projects.git
    dest={{ redmine_dir }}/plugins/favourite_projects

- name: install omniauth_saml plugin
  git:
    repo=https://github.com/chrodriguez/redmine_omniauth_saml.git
    dest={{ redmine_dir }}/plugins/omniauth_saml
    
#- name: install knowledgebase plugin
#  git:
#    repo=https://github.com/alexbevi/redmine_knowledgebase.git
#    dest={{ redmine_dir }}plugins/redmine_knowledgebase

# [TODO] RM+ Userbility
# [TODO] RM+ Custom Menu
# [TODO] Redmine Time Logger plugin
# [TODO] Redmine Default Custom Query
# [TODO] Redmine Issue Templates plugin
# [TODO] Easy Gantt
# [TODO] Knowledgebase

- name: install plugin gems
  command:
    bundle install --no-deployment
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: update gems
  command:
    bundle update
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: migrate redmine-database
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: migrate plugins-database
  command:
    bundle exec rake redmine:plugins:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
 