---
- name: install farend_basic theme
  git:
    repo=https://github.com/farend/redmine_theme_farend_basic.git
    dest={{ redmine_dir }}/public/themes/farend_basic

- name: install gitmike theme
  git:
    repo=https://github.com/makotokw/redmine-theme-gitmike.git
    dest={{ redmine_dir }}/public/themes/gitmike

- name: install circle theme
  unarchive: 
    src=https://www.redminecrm.com/license_manager/29210/circle_theme-2_1_0.zip
    dest={{ redmine_dir }}/public/themes
    copy=no

# unarchive task can talk http, but it can't use proxy.
- name: install circle theme
  get_url:
    url: https://www.redminecrm.com/license_manager/29210/circle_theme-2_1_0.zip
    dest: /tmp
    validate_certs: false

- name: expand circle theme
  command:
    chdir={{ redmine_dir }}/public/themes
    unzip -f /tmp/circle_theme-2_1_0.zip
