# postgresql-server : dbms
# python-psycopg2 : ansible postgres* modules needs psycopg2
- name: Install PostgreSQL
  yum: name="{{ item }}" state=present
  with_items:
    - "postgresql-server"
    - "python-psycopg2"

- name: PostgreSQL initdb
  command:
    postgresql-setup initdb
  register:
    initdb_result
  failed_when: initdb_result.rc not in [0, 1]
  changed_when: initdb_result.rc == 0

- name: append access settings
  lineinfile:
    dest=/var/lib/pgsql/data/pg_hba.conf
    insertafter="#[ ]+TYPE[ ]+DATABASE[ ]+USER[ ]+ADDRESS[ ]+METHOD"
    line={{ item }}
  with_items:
    - 'host    {{ db_name }}         {{ db_name }}         127.0.0.1/32            md5'
    - 'host    {{ db_name }}         {{ db_name }}         ::1/128                 md5'

- name: PostgreSQL service setup
  service:
    name=postgresql
    state=restarted
    enabled=yes

- name: Create db
  sudo: yes
  sudo_user: postgres
  postgresql_db:
    name={{ db_name }}
    encoding='UTF-8'
    lc_collate='ja_JP.UTF-8'
    lc_ctype='ja_JP.UTF-8'
    template='template0'

- name: create user
  sudo: yes
  sudo_user: postgres
  postgresql_user:
    db={{ db_name }}
    name={{ db_name }}
    password={{ db_passwd }}
    priv=ALL
    state=present
    login_user=postgres
